### PR TITLE
Sadconsole v3

### PR DESCRIPTION
**Pull request by Thraka**
Opening the pull request for v3. Not going to accept the PR just yet. I'll keep doing reviews. I've also been upgrading the SadConsoleEditor project for v3, once that is done and working, this PR will be accepted.

### CODE REVIEW

**Comment by arxae** [comment]
Do you have an ETA when V3 will be completed?

**Comment by Thraka** [comment]
Any day. I'm just spending my nights touching things up. I'm trying to reimplement the Entity class as something else. I think that is my last thing to do. Then I have to write an article to help people convert from 2.x to 3.x

**Comment by arxae** [comment]
Any plans for RogueSharp compatibility? In the sense that you use XNA Point and they have their own point class. Or do we have to stick to our own conversion methods/extensions?

**Comment by arxae** [comment]
In the meantime i made a conversion of the library to use the MonoGame Point class (Repo [here](https://github.com/arxae/RogueSharp)).

Until we find a solution that is a bit better of course :D

**Comment by Thraka** [comment]
I'm going to call this good. The only remaining things I need to do 

1. Build out nuget packages
2. Update the repository README.md
3. Archive master branch 

If you want, feel free to pull this branch down and compile if you want to look at V3.

**Pull request merged**
