### PR TITLE
Corrected a small bug in EntityLiteConsole.

### PR DESCRIPTION
**Pull request by RychuP**
In develop branch as requested.

### CODE REVIEW

**Comment by adegeo** [comment]
@RychuP Why did you close this? I'm willing to accept it :)

**Comment by Thraka** [comment]
Why did you close this? I'm willing to accept it :)

**Comment by RychuP** [comment]
I am sure you've corrected it by now. But here it comes again, my first, hopefully to be accepted, pull request :)

**Comment by RychuP** [comment]
Beautiful. Thank you.

**Pull request merged**
